line-length = 79
indent-width = 4

[lint]
select = ["E4", "E7", "E9", "F"]
ignore = ["F403"]
exclude = ["mount/app/models/__init__.py", "mount/alembic", "*.pyi"]

[format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true
docstring-code-line-length = 20
exclude = ["mount/alembic", "*.pyi"]
