"""fix_author_id

Revision ID: 51fe191fe0a5
Revises: 4f37505887dd
Create Date: 2025-06-27 17:45:15.542983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51fe191fe0a5'
down_revision: Union[str, Sequence[str], None] = '4f37505887dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'author_id')
    # ### end Alembic commands ###
