"""fix_update_onupdate

Revision ID: b86ff46aa9e5
Revises: 451b3b79e1c4
Create Date: 2025-06-27 19:28:27.879187

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b86ff46aa9e5'
down_revision: Union[str, Sequence[str], None] = '451b3b79e1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		'articles', sa.Column('category_id', sa.Integer(), nullable=False)
	)
	op.create_foreign_key(
		None, 'articles', 'categories', ['category_id'], ['id']
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint(None, 'articles', type_='foreignkey')
	op.drop_column('articles', 'category_id')
	# ### end Alembic commands ###
