"""tag_array_added_in_article

Revision ID: e4a9ab728141
Revises: 0720aedb9093
Create Date: 2025-06-28 11:10:13.178846

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4a9ab728141'
down_revision: Union[str, Sequence[str], None] = '0720aedb9093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		'articles',
		sa.Column('tags', postgresql.ARRAY(sa.TEXT()), nullable=True),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('articles', 'tags')
	# ### end Alembic commands ###
